#ifndef INTERRUPT_H
#define INTERRUPT_H

#define STR(...) #__VA_ARGS__
#define ASM(...) STR(__VA_ARGS__)

#define INTERRUPT_BIOS_VIDEO 0x10
#define INTERRUPT_BIOS_EQUIPMENT 0x11
#define INTERRUPT_BIOS_KEYBOARD 0x16
#define INTERRUPT_BIOS_PRINTER 0x17
#define INTERRUPT_DOS 0x21

#define BIOS_VIDEO_MODE 0x00
#define BIOS_VIDEO_CARET_SHAPE 0x01
#define BIOS_VIDEO_CARET_POSITION 0x02
#define BIOS_VIDEO_SCROLL_DOWN 0x07

#define BIOS_KEYBOARD_EXTENDED_CHARACTER 0x10
#define BIOS_KEYBOARD_EXTENDED_STATUS 0x11

#define BIOS_PRINTER_WRITE 0x00
#define BIOS_PRINTER_INITIALIZE 0x01
#define BIOS_PRINTER_STATUS 0x02

#define DOS_WRITE_STDOUT 0x02
#define DOS_GET_TIME 0x2C
#define DOS_GET_DTA 0x2F
#define DOS_DIRECTORY_CREATE 0x39
#define DOS_FILE_OPEN 0x3D
#define DOS_FILE_CREATE_OR_TRUNCATE 0x3C
#define DOS_FILE_CLOSE 0x3E
#define DOS_FILE_READ 0x3F
#define DOS_FILE_WRITE 0x40
#define DOS_FILE_SEEK 0x42
#define DOS_MEMORY_ALLOCATE 0x48
#define DOS_MEMORY_FREE 0x49
#define DOS_MEMORY_REALLOCATE 0x4A
#define DOS_FIND_FIRST_FILE 0x4E
#define DOS_FIND_NEXT_FILE 0x4F
#define DOS_EXEC 0x4B
#define DOS_GET_VARIABLES 0x52
#define DOS_FILE_RENAME 0x56
#define DOS_FILE_CREATE 0x5B
#define DOS_QUERY_PSP 0x62

#endif

