CC = wcc
CFLAGS = -1 -za99 -d0 -oxs -zq
LD = wlink

all: args.obj file.obj text.obj output.obj input.obj exeparse.obj unlzexe.obj bstream.obj memory.obj error.obj

.c.obj:
    $(CC) -fo=$@ $(CFLAGS) $<

clean: .symbolic
    del *.obj
    del *.err
