@ECHO OFF

:START
CLS
@ECHO [0;1m[70C[33mÜÜÛÛÛÛ[0;33mÜ
@ECHO [63C[1mÜÜ  ÛÛ[0;33mÜ[1mÛÛ[0;33mÛßßßß
@ECHO [6C[1;35mA Fantastic Adventure of[24C[33mÜÜÜÜÛÛÛ[0;33mÜ[1mÜÛ[43mß[0;33mÛ[1mÛÛ[0;33mÛ[1;43mÜ[40mÛÛ[43mÜ[40mÛ[0;33mÜ
@ECHO [6C[1;35mExploration and Survival[15C[33mÜÜÜÜÜ    ßÛÛÛ[43mß[0;33mÛßß[1mÛÛ[43mÜ[40mÛÛ[0;33mÛß[1mÛÛ[43mßß[0;33mÛß
@ECHO [36C[1mÜ   ÛÛ[0;33mÜ [1mÛÛ[43mß[40mÛÛÛÛ[0;33mÜ   [1mÜÛ[43mß[0;33mÛ   [1mÛ[43mßß[40mÛÛ[0;33mÛ[1mÜÛÛ[43mÜ[40mÜÛ[0;33mÜ
@ECHO [30C[1mÜÜ   ÛÛÛ[0;33mÜ [1mÛÛ[0;33mÛ [1mÛ[43mß[0;33mÛ [1mÜÛÛ[0;33mÛ   [1mÛÛ[0;33mÛ   [1mÛÛ[0;33mÛ [1mÛÛ[0;33mÛ[1mßÛ[43mßßß[0;33mÛß
@ECHO [23C[1mÜÜ   ÜÛÛÛÛ[0;33mÜ [1mÛÛÛÛÜÛ[0;33mÛß[1mÛÛ[0;33mÛ  [1mÛÛ[0;33mÛß  [1mÜÛ[43mß[0;33mÛ   [1mÛ[43mß[0;33mÛ [1mß[0;33mÛß  ß
@ECHO [18C[1mÜÛ[0;33mÜ  [1mÛÛ[0;33mÛ[1mÜÛ[43mß[0;33mÛß[1mÛÛ[0;33mÛ[1mÛÛ[0;33mÛ[1mßÛÛÛ[0;33mÛ [1mÛÛ[0;33mÛ[1mÜÛ[43mß[0;33mÛß   [1mÛ[43mß[0;33mÛ[5C[1;43mÜ[40mÜÜ   [0;33m(tm)
@ECHO [11C[1mÜÜÛÛÛÛ[0;33mÜ[1mÛÛ[43mÜ[2C[40mÛÛ[0;33mÛ[1mÛÛ[0;33mÛ  [1mÛ[43mß[0;33mÛ[1mÛÛ[0;33mÛ[1mÜÛÛ[0;33mÛß[1mßÛÛÛ[43mß[0;33mÛß[6C[1;43mÜ[40mÜ   ÜÛ[43mßß[0;33mÛß
@ECHO     [1mÜÛÛÛÛ[43mß[0;33mÜ[1mÛÛ[0;33mÛßßßß[1mÛÛÛÛÛ[43mß[0;33mÛ[1;43mÜ[40mÛ[43mÜ[0;33mß[1mÜÛ[43mß[0;33mÛ[1mßÛÛ[0;33mÛ [1mß[43mß[0;33mÛ   ßßß[1mÜ   ÛÛ[0;33mÜ [1mÛÛ[0;33mÛ[1mÜÛÛ[0;33mÛß
@ECHO    [1mÜÛ[0;33mÛß[1mÛÛ[0;33mÛ[1mÜÛÛ[43mÜ[40mÛ[0;33mÜ   [1mßÛÛ[0;33mÛß  [1mÛÛÛÛ[43mß[0;33mÛ  [1mß[0;33mÛß  [1mÜÜ[5CÛÛÛ[0;33mÜ [1mÛÛ[0;33mÛ [1mÛ[43mß[0;33mÛ[1mÛÛ[0;33mÛß
@ECHO    [1mÛÛÛÛ[43mß[0;33mÛß[1mÛÛ[43mßß[0;33mÛß[1mÜÜÜÛ[43mß[0;33mÛß    [1mß[0;33mÛßß [1mÜÜÜ   ÛÛÛÛ[0;33mÜ   [1mÛÛÛÛÜÛ[0;33mÛß[1mÛÛ[0;33mÛ[1mÜÛÛ[43mÜ[2C[40mÜÛ[0;33mÜ
@ECHO   [1mÜÛ[43mßß[40mÛÛ[0;33mÜ[1mÜÛÛ[43mÜ[40mÜÛ[0;33mÜ[1mß[43mßß[0;33mÛß   [1mÜÜ  ÛÛÛÛÛ[43mßß[0;33mÛ [1mÛÛ[0;33mÛ[1mÛÛ[0;33mÛ  [1mÛÛ[0;33mÛ[1mßÛÛÛ[0;33mÛ[1mÜÛ[43mß[0;33mÛ [1mßÛÛÛÛ[43mß[0;33mÛß
@ECHO   [1mÛÛ[43mÜ[40mÜÛ[43mß[0;33mÛ[1mßÛ[43mßßß[0;33mÛß[1mÜÜÜÜÛÛÛ[0;33mÜ[1mÛÛ[0;33mÛ  [1mßÛÛ[0;33mÛß  [1mÛÛ[43mß[0;33mÛ[1mÜÛÛ[0;33mÜ [1mÛÛ[0;33mÛ[1mÜÛÛ[0;33mÛß[1mÛÛ[0;33mÛ    ßßßß
@ECHO   [1mß[43mßßß[0;33mÛß   ß    [1mßÛÛÛ[43mß[0;33mÛßß[1mÛ[43mß[0;33mÛ  [1mÛÛ[0;33mÛß  [1mÜÛÛÛÛ[43mß[40mÛÛ[0;33mÛ[1mßÛÛ[0;33mÛ [1mß[43mß[0;33mÛ  ßß
@ECHO [17C[1mÜÛ[43mß[0;33mÛ  [1mÛÛ[0;33mÛ  [1mÜÛÛ[0;33mÛ  [1mÛÛ[43mß[0;33mÛßßß[1mÛ[43mß[0;33mÛ [1mß[0;33mÛß
@ECHO [17C[1mÛÛ[0;33mÛ  [1mÜÛ[43mß[0;33mÛ  [1mÛÛ[0;33mÛß  [1mß[43mß[0;33mÛ[5Cß[8C[1;31mDesigned by Scott Miller
@ECHO [16C[33mÜÛ[43mß[0;33mÛ  [1mÛÛ[0;33mÛ   [1mß[0;33mÛß[18C[0;31mAn Apogee Software Production
@ECHO [16C[1;33mÛ[43mß[0;33mÛ    ßß
@ECHO [17Cß[1m
@ECHO                                [37mS[33mtart the game
@ECHO                                 [37mH[33melp & hints
@ECHO                                 [37mI[33mnstructions
@ECHO                                     [37mQ[33muit
@ECHO [0;30m                                                                              ÿ[00;37;40m[1A[s

:CHOICES
@CHOICE /N /C:SHIQ
IF ERRORLEVEL 4 GOTO EXIT
IF ERRORLEVEL 3 GOTO HELPSHEET
IF ERRORLEVEL 2 GOTO HINTSHEET
IF ERRORLEVEL 1 GOTO GAME

:HINTSHEET
IF EXIST HELP.DOC SET TITANICHINT=HELP.DOC
IF EXIST HELP.TXT SET TITANICHINT=HELP.TXT
CLS
TYPE %TITANICHINT%
PAUSE
GOTO START

:HELPSHEET
IF EXIST INSTRUCT.DOC SET TITANICHELP=INSTRUCT.DOC
IF EXIST INSTRUCT.TXT SET TITANICHELP=INSTRUCT.TXT
LIST %TITANICHELP% > NUL
IF NOT ERRORLEVEL 1 GOTO START
LESS %TITANICHELP% > NUL
IF NOT ERRORLEVEL 1 GOTO START
MORE < %TITANICHELP% > NUL
IF NOT ERRORLEVEL 1 GOTO START
CLS
ECHO LIST, LESS or MORE required to display instructions.
PAUSE
GOTO START

:NOTFOUND
ECHO Stuff not found
PAUSE
GOTO START

:LISTHELP
LIST %TITANICHELP%
GOTO START

:MOREHELP
MORE %TITANICHELP%
GOTO START

:GAME
BEYOND
GOTO START

:EXIT
SET TITANICHELP=
SET TITANICHINT=
CLS
