@ECHO OFF

:START
SET CHOICES=3
CLS
ECHO [?7h[40m[2J[40m[0;1m  [0;33m(tm)  [1mÜÜÜÜ   ÜÜÜ[5CÜÜÜÜÜ[5CÜÜÜÜÜ[5CÜÜÜ[5CÜÜÜ    ÜÜÜÜ    ÜÜÜÜÜ  ÜÜÜÜ
ECHO [6CÜÛÛßßß ÜÛßßÛÛ  ÜÛßÛÛßÛÛ  ÜÛßÛÛßÛÛ  ÜÛßßÛÛ  ÜÛßßÛÛ  ÜÛßßÛÛ  ÜÛßßßß ÜÛßßÛÛ
ECHO [6C[37mÛÛ[5CÛÛ  ÛÛ  ÛÛ ÛÛ ÛÛ  ÛÛ ÛÛ ÛÛ  ÛÛ  ÛÛ  ÛÛ  ÛÛ  ÛÛ  ÛÛ  ÛÛ[5CÛÛ  ÛÛ
ECHO [5C[0;33mÜ[1;37;43mß[40mß    [0;33mÜ[1;37;43mß[40mß [0;33mÜ[1;37;43mß[40mß [0;33mÜ[1;37;43mß[40mß[0;33mÜ[1;37;43mß[40mß[0;33mÜ[1;37;43mß[40mß [0;33mÜ[1;37;43mß[40mß[0;33mÜ[1;37;43mß[40mß[0;33mÜ[1;37;43mß[40mß [0;33mÜ[1;37;43mßßßßß[40mß [0;33mÜ[1;37;43mß[40mß [0;33mÜ[1;37;43mß[40mß [0;33mÜ[1;37;43mß[40mß [0;33mÜ[1;37;43mß[40mß [0;33mÜ[1;37;43mßßßß[40mß [0;33mÜ[1;37;43mßßßß[40mß
ECHO [5C[0;33mÛÛ[5CÛÛ  ÛÛ  ÛÛ ÛÛ ÛÛ  ÛÛ ÛÛ ÛÛ  ÛÛ  ÛÛ  ÛÛ  ÛÛ  ÛÛ  ÛÛ  ÛÛ[5CÛÛ  ÛÛ
ECHO [5C[1mÛÛÜÜ   ÛÛÜÜÛß ÜÛßÜÛßÜÛß ÜÛßÜÛßÜÛß ÜÛß ÜÛß ÜÛß ÜÛß ÜÛÛÜÜÛß ÜÛÛÜÜ  ÜÛß ÜÛß
ECHO [6Cßßß    ßßß   ßß ßß ßß  ßß ßß ßß  ßß  ßß  ßß  ßß  ßßßßß   ßßßßß  ßß  ßß
ECHO    ÜÜ  ÜÜ  ÜÜÜÜÜ  ÜÜÜÜÜ   ÜÜÜ[7C[37m"ÖÄÄ¿ ÖÄÄ¿ ÖÄÄ¿ ÄÒÄÄ¿ ÒÄ¿  Ò  Â ÒÄÄ¿
ECHO   [33mÜÛß ÜÛß ÜÛßßßß ÜÛßßßß ÜÛßßÛÛ[7C[37mº Ä¿ º  ³ º  ³  º  ³ ÇÄÁ¿ ÓÄÄ´ ÇÄ
ECHO   ÛÛ  ÛÛ  ÛÛ[5CÛÛ[5CÛÛ  ÛÛ[7CÓÄÄÙ ÓÄÄÙ ÓÄÄÙ ÄÐÄÄÙ ÐÄÄÙ ÓÄÄÙ ÐÄÄÙ
ECHO  [0;33mÜ[1;37;43mßßßß[40mß  [0;33mÜ[1;37;43mßßßß[40mß [0;33mÜ[1;37;43mßßßß[40mß [0;33mÜ[1;37;43mß[40mß [0;33mÜ[1;37;43mß[40mß[10CÖÄÄ¿ ÖÄÄ¿ Ò    ÖÄÄ¿ Ä· Ú Ò  Â"
ECHO  [0;33mÛÛ  ÛÛ  ÛÛ[5CÛÛ[5CÛÛ  ÛÛ[11C[1;37mº Ä¿ ÇÄÄ´ º    ÇÄÄ´ ÖÐÂÙ ÓÄÄ´
ECHO [33mÜÛß ÜÛß ÜÛÛÜÜ  ÜÛÛÜÜ  ÜÛß ÜÛß[11C[37mÓÄÄÙ Ð  Á ÐÄÄÙ Ð  Á ½ ÀÄ ÓÄÄÙ
ECHO [33mßß  ßß  ßßßßß  ßßßßß  ßß  ßß                     [16C[0;33mÜÜÜÜÜÜÜÜ[1;36m
ECHO                                                       [9C[0;33mÜ[1;43mÜ[40mÛÛÛÛÛÛÛÛ[43mÜ[0;33mÜ[1;36m
ECHO            [1;31mCopyright 1991 Id Software Inc.            [7C[0;33mÜ[1;43mÜ[40mÛÛÛÛ[42mß      ß[43mÜ[0;33mÜ[1;36m
ECHO             [0;31mPublished by Apogee Software              [5C[0;33mÜ[1;43mÜ[42mÛÛÛÛÛ  ÜÛÛß    Û[43mÜ[0;33mÜ[1;36m
ECHO                                                       [5C[0;33mÛ[1mÛ[42mÛÛÛÛÛ      ÜÛ  ÛÛ[0;33mÛ[1;36m
ECHO                 [1;33m-- SELECT AN EPISODE --               [8C[1;33mßÛÛÛ[42m  ÛÜ  ßÛ  ÛÛ[0;33mÛ[1;36m
ECHO                [0;35m1) Secret of the Oracle                [10C[1;33;42mÛ[40mÛ[42m  ßÛÛÜ    ÛÛ[0;33mÛ[1;36m
ECHO                [0;35m2) The Armageddon Machine              [10C[1;33;42mÛÛÛ[30mÜÛÛ    [33mÜÛÛ[43mß[0;33mß[1;36m
ECHO                                                       [0;37mÜÛÛÛ[47m  [1;30mÜÛ[43mß[47mÛ[43mÛÛÛ[42mÛ[43mß[33mÜ[42mÛÛÛÛÛ[43mß[0;33mß[1;36m
ECHO                [1;31m3) [1;36mExit                                [6C[1;30;43mÛÛÜÜÛÛß[33mÜÛÛÛÛÛß[0;33mß[1;36m
ECHO                                                       [0;37mßÛÛÛ[47m   [1;30mß[43mÛÛß[33mÜ[40mÛÛÛÛÛ[43mß[0;33mß[1;36m
@ECHO [00;30;40mÿ[01;32;40mÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ[00;37;40m[1A[s
GOTO COSMETICS

:COSMETICS
IF EXIST GG-HINT.EXE GOTO COS92
IF EXIST GGHINT.EXE GOTO COS92
IF EXIST DEALERS.EXE GOTO COS92
IF EXIST SWCBBS.EXE GOTO COS92
IF EXIST KEEN5.EXE GOTO COSGT
IF EXIST KEEN4.EXE GOTO COSGT
IF EXIST KEEN.EXE GOTO COSFGDM
GOTO EP2CHECK

:COS92
@ECHO [16;25H[01;31;40m2[00;37;40m[u
GOTO EP2CHECK

:COSFGDM
@ECHO [17;11H[01;37;40m      SPECIAL DEMO VERSION      [00;37;40m[u
GOTO EP1CHECK

:COSGT
@ECHO [16;25H[01;31;40m2[00;37;40m[u
@ECHO [17;12H[00;31;40mPublished by Goodtimes Software[00;37;40m[u
GOTO EP2CHECK

:EP2CHECK
IF EXIST KEEN5E.EXE GOTO EP2ENABLE
IF EXIST KEEN5.EXE GOTO EP2ENABLE
IF EXIST KEEN5C.EXE GOTO EP2ENABLE
SET CHOICES=%CHOICES%ÿ
GOTO EP1CHECK

:EP1CHECK
IF EXIST KEEN4E.EXE GOTO EP1ENABLE
IF EXIST KEEN4.EXE GOTO EP1ENABLE
IF EXIST KEEN.EXE GOTO EP1ENABLE
IF EXIST KEEN4C.EXE GOTO EP1ENABLE
SET CHOICES=%CHOICES%ÿ
GOTO CHOICES

:EP2ENABLE
SET CHOICES=%CHOICES%2
@ECHO [21;16H[01;31;40m2) [01;35;40mThe Armageddon Machine[00;37;40m[u
GOTO EP1CHECK

:EP1ENABLE
SET CHOICES=%CHOICES%1
@ECHO [20;16H[01;31;40m1) [01;35;40mSecret of the Oracle[00;37;40m[u
GOTO CHOICES

:CHOICES
@CHOICE /N /C%CHOICES% >> NUL
IF ERRORLEVEL 3 GOTO KEEN4
IF ERRORLEVEL 2 GOTO KEEN5
IF ERRORLEVEL 1 GOTO EXIT

:KEEN4
IF EXIST KEEN4E.EXE KEEN4E %1 %2 %3 %4 %5 %6 %7 %8 %9
IF EXIST KEEN4.EXE KEEN4 %1 %2 %3 %4 %5 %6 %7 %8 %9
IF EXIST KEEN.EXE KEEN %1 %2 %3 %4 %5 %6 %7 %8 %9
IF EXIST KEEN4C.EXE KEEN4C %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO START

:KEEN5
IF EXIST KEEN5E.EXE KEEN5E %1 %2 %3 %4 %5 %6 %7 %8 %9
IF EXIST KEEN5.EXE KEEN5 %1 %2 %3 %4 %5 %6 %7 %8 %9
IF EXIST KEEN5C.EXE KEEN5C %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO START

:EXIT
CLS